# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rlemmens/youtube-sync
  pullPolicy: IfNotPresent
  tag: "0.1.0"
podAnnotations:
  linkerd.io/inject: enabled

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

httproute:
  enabled: true
  host: youtube-sync.nl

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
